### ISSUE TITLE
Can be considered compatible with windows？

### ISSUE THREAD

**Issue by sylvoslee** [fluidattacks/aioextensions#1]

**Comment by kamadorueda** [comment]
I've never tried, but I believe it should work: the library is just a wrapper around the standard library to make things more human friendly

One of the easiest way to know if it works correctly is to install `aioextensions` and `pytest` in your windows system,
then run `pytest` from the `test` folder of this repo

![image](https://user-images.githubusercontent.com/47480384/99675127-d4b97a00-2a44-11eb-98af-f1a73428e4cb.png)

If something goes wrong let me know! sure thing we can fix it

**Comment by sylvoslee** [comment]
Because uvloop does not work on Windows

**Comment by kamadorueda** [comment]
let's keep it open, I'll make uvloop optional so it works on windows

thanks!

**Comment by kamadorueda** [comment]
@sylvoslee I just released 20.11.1621472, please let me know if you can install and use it on Windows

**Comment by sylvoslee** [comment]
thank you,it can works on windows now
